include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

image: node:latest

stages:
  - checks
  - build
  - test

cache:
  paths:
    - node_modules/
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    
Test:
  stage: checks
  script:
    - yarn install
    - yarn test

Build Linux:
  image: electronuserland/builder:latest
  stage: build
  script:
    - yarn install
    - yarn build --linux AppImage --x64
  artifacts:
    paths:
      - dist/broadcast-em-*
    expire_in: 6h

Build Winodws:
  image: electronuserland/builder:wine
  stage: build
  script:
    - yarn install
    - yarn build --windows portable --x64
  artifacts:
    paths:
      - dist/broadcast-em-*
    expire_in: 6h
