image: electronuserland/builder:latest

stages:
  - check
  - deploy

cache:
  paths:
    - node_modules/
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

Test:
  stage: check
  script:
    - yarn install
    - yarn test

Build:
  stage: check
  script:
    - yarn install
    - yarn build --publish never --linux --win

Release:
  stage: deploy
  when: manual
  script:
    - yarn install
    - yarn build
