image: node:latest

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

Test:
  stage: test
  script:
    - yarn install
    - yarn test

Build:
  stage: build
  script:
    - yarn install
    - yarn build
