# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

Test:
  stage: test
  script:
    - yarn install
    - yarn test
  stage: build
  script:
    - yarn install
    - yarn build --publish never
Release:
  when: manual
  script:
    - yarn install
    - yarn build
